news_sites:
  axum_94:
    url: http://www.axum.com.ar/1994srl/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
  axum_kg:
    url: http://www.axum.com.ar/keraguazu/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
