news_site:
  axum_94: #http://www.axum.com.ar/1994srl/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
    url: http://www.axum.com.ar/1994srl/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
  axum_kg: #http://www.axum.com.ar/keraguazu/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
    url: http://www.axum.com.ar/keraguazu/controllerView.aspx?cmd=AxDplusDashboards&mode=kpis
